In [4]:
import numpy as np

In [9]:
m= [[1,2,3],[3,4,5],[6,7,8]]
x=np.array(m)
m
print(m[0])
print(m[0][1])

[1, 2, 3]
2


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
m.shape

(3, 2)

In [8]:
m.ndim

2

In [14]:
m.size

6

In [58]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arreglo= np.arange(0,25)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
arreglo.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
m= np.concatenate((x, y), axis=0)
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [11]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [12]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [13]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [14]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [25]:
x = np.array([[1, 1], [2, 2]])

print(x.sum())
print(x.sum(axis=0))# suma renglones
print(x.sum(axis=1))# suma columnas

6
[3 3]
[2 4]


In [34]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x)
x.min()
x.max()
x.min(axis=0) #minimo por columna
x.min(axis=1) #minimo por renglon

[[1 3 5]
 [2 4 6]]


array([1, 2])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x.reshape(3,2))
print(x.transpose())
print(x.T)

[[1 3]
 [5 2]
 [4 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [50]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [51]:
reversed_arr_rows = np.flip(arr_2d, axis=0) #renglones
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [52]:
reversed_arr_columns = np.flip(arr_2d, axis=1) #columnas
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [53]:
arr_2d[1] = np.flip(arr_2d[1])
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 5  6  7  8]
 [12 11 10  9]]


In [5]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
a1 = x.flatten() #no afecta al original
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
a2 = x.ravel() #si afecta al original
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
x[1:,1:3]

array([[ 6,  7],
       [10, 11]])